# Generated by Django 4.2.6 on 2023-10-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stop_set',
            field=models.ManyToManyField(through='bus_data.RouteStop', to='bus_data.stop'),
        ),
    ]
