# Generated by Django 4.2.6 on 2023-10-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_data', '0002_route_stop_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_data.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_data.stop')),
            ],
        ),
    ]
