# Generated by Django 4.2.6 on 2023-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_notifiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifier',
            name='direction',
            field=models.CharField(choices=[(1, 'Departure'), (2, 'Return')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
