# Generated by Django 4.2.6 on 2023-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_notifiers', '0002_notifier_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifier',
            name='last_notified_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
