# Generated by Django 4.2.6 on 2023-10-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_notifiers', '0003_notifier_last_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='direction',
            field=models.IntegerField(choices=[(1, 'Departure'), (2, 'Return')]),
        ),
    ]
